# Operaciones sobre ndarrays

NumPy pone a nuestra disposición un amplio conjunto de funciones optimizadas para aplicar sobre ndarrays de forma global evitando así la necesidad de utilizar bucles (mucho más costosos).

In [1]:
import numpy as np

import warnings; warnings.simplefilter('ignore')

### Operaciones elemento a elemento - Universal functions

El primero de los conjuntos de funciones ofrecido por NumPy son las llamadas "funciones universales" (o ufuncs) que permiten la realización de operaciones elemento a elemento de un array. En función del número de parámetros encontramos dos tipos de funciones universales.

#### Funciones unarias

Son aquellas funciones que reciben como parámetro un único ndarray.<br/>
<ul>
<li><b>abs, fabs:</b> Valor absoluto.</li>
<li><b>sqrt:</b> Raíz cuadrada (equivalente a array \*\* 0.5).</li>
<li><b>square:</b> Potencia al cuadrado (equivalente a array ** 2).</li>
<li><b>exp:</b> Potencia de e.</li>
<li><b>log, log10, log2, log1p:</b> Logaritmos en distintas bases.</li>
<li><b>sign:</b> Signo (+ = 1 / - = -1 / 0 = 0).</li>
<li><b>ceil:</b> Techo.</li>
<li><b>floor:</b> Suelo.</li>
<li><b>rint:</b> Redondeo al entero más cercano.</li>
<li><b>modf:</b> Devuelve dos arrays uno con la parte fraccionaria y otro con la parte entera.</li>
<li><b>isnan:</b> Devuelve un array booleano indicando si el valor es NaN o no.</li>
<li><b>isfinite, isinf:</b> Devuelve un array booleano indicando si el valor es finito o no.</li>
<li><b>cos, cosh, sin, sinh, tan, tanh:</b> Funciones trigonométricas.</li>
<li><b>arccos, arccosh, arcsin, arcsinh, arctan, arctanh:</b> Funciones trigonométricas inversas.</li>
<li><b>logical_not:</b> Inverso booleano de todos los valores del array (equivalente a -(array)).</li>
</ul>

Algunos ejemplos:

In [2]:
array = np.random.randn(2, 5)

print("array:\n",array, "\n")

print("valor absoluto:\n", np.abs(array), "\n")
print("raiz cuadrada:\n", np.sqrt(array), "\n")
print("exponencial:\n", np.exp(array), "\n")
print("logaritmo natural:\n", np.log(array), "\n")
print("floor:\n", np.floor(array), "\n")
print("ceil:\n", np.ceil(array), "\n")
print("valores nan:\n", np.isnan(np.sqrt(array)), "\n")

array:
 [[ 0.03432347 -0.22727251 -0.24200645  1.13137272 -0.1936286 ]
 [-0.43116828 -1.95191745  0.0800655  -0.98793886 -1.29347029]] 

valor absoluto:
 [[0.03432347 0.22727251 0.24200645 1.13137272 0.1936286 ]
 [0.43116828 1.95191745 0.0800655  0.98793886 1.29347029]] 

raiz cuadrada:
 [[0.18526594        nan        nan 1.06366006        nan]
 [       nan        nan 0.28295848        nan        nan]] 

exponencial:
 [[1.03491932 0.79670364 0.78505111 3.0999089  0.82396387]
 [0.64974956 0.14200153 1.08335803 0.37234335 0.27431717]] 

logaritmo natural:
 [[-3.3719259          nan         nan  0.1234317          nan]
 [        nan         nan -2.52491018         nan         nan]] 

floor:
 [[ 0. -1. -1.  1. -1.]
 [-1. -2.  0. -1. -2.]] 

ceil:
 [[ 1. -0. -0.  2. -0.]
 [-0. -1.  1. -0. -1.]] 

valores nan:
 [[False  True  True False  True]
 [ True  True False  True  True]] 



#### Funciones binarias

Son aquellas funciones que reciben como parámetro dos arrays.
<ul>
<li><b>add:</b> Adición de los elementos de los dos arrays (equivalente a array1 + array2).</li>
<li><b>subtract:</b> Resta de los elementos de los dos arrays (equivalente a array1 - array2).</li>
<li><b>multiply:</b> Multiplica los elementos de los dos arrays (equivalente a array1 \* array2).</li>
<li><b>divide, floor_divide:</b> Divide los elementos de los dos arrays (equivalente a array1 / (o //) array2).</li>
<li><b>power:</b> Eleva los elementos del primer array a las potencias del segundo (equivalente a array1 ** array2).</li>
<li><b>maximum, fmax:</b> Calcula el máximo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>minimum, fmin:</b> Calcula el mínimo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>mod:</b> Calcula el resto de la división de los dos arrays (equivalente a array1 % array2).</li>
<li><b>greater, greater_equal, less, less_equal, equal, not_equal:</b> Comparativas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
<li><b>logical_and, logical_or, logical_xor:</b> Operaciones booleanas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
</ul>

Algunos ejemplos:

In [3]:
array1 = np.random.random_integers(10, size=(2,5))
array2 = np.random.random_integers(10, size=(2,5))

print("array1:\n",array1, "\n")
print("array2:\n",array2, "\n")

print("suma:\n", np.add(array1,array2), "\n")
print("resta:\n", np.subtract(array1,array2), "\n")
print("multiplicación:\n", np.multiply(array1,array2), "\n")
print("división:\n", np.divide(array1,array2), "\n")
print("potencia:\n", np.power(array1,array2), "\n")
print("máximo:\n", np.maximum(array1,array2), "\n")
print("mayor que:\n", np.greater(array1,array2), "\n")

array1:
 [[1 4 5 3 7]
 [7 4 6 4 5]] 

array2:
 [[7 7 3 3 4]
 [9 4 3 5 4]] 

suma:
 [[ 8 11  8  6 11]
 [16  8  9  9  9]] 

resta:
 [[-6 -3  2  0  3]
 [-2  0  3 -1  1]] 

multiplicación:
 [[ 7 28 15  9 28]
 [63 16 18 20 20]] 

división:
 [[0.14285714 0.57142857 1.66666667 1.         1.75      ]
 [0.77777778 1.         2.         0.8        1.25      ]] 

potencia:
 [[       1    16384      125       27     2401]
 [40353607      256      216     1024      625]] 

máximo:
 [[7 7 5 3 7]
 [9 4 6 5 5]] 

mayor que:
 [[False False  True False  True]
 [False False  True False  True]] 



### Selección de elementos de ndarrays en función de una condición

NumPy pone a nuestra disposición, a través de la función <b>np.where</b> la posibilidad de generar un array de salida a partir de dos de entrada, estableciendo una máscara booleana que indique si (elemento a elemento) debemos enviar a la salida el elemento del primer ndarray (valor True) o del segundo (valor False).

In [4]:
array1 = np.random.randn(5,5)
array2 = np.random.randn(5, 5)

print("array1:\n",array1,"\n")
print("array2:\n",array2)

print("\nFusión condicional:")
print(np.where(array1 < array2, array1, array2))

print("\nAnidación de condiciones:")
print(np.where(array1 < array2, np.where(array1 < 0, 0, array1), array2))

array1:
 [[-0.32191201 -1.52187377 -0.4887973   0.57624139 -1.16257721]
 [-0.91951481 -1.21703311 -0.23323835 -0.27868128 -1.58374534]
 [ 0.88665692  0.85020783  0.2738285  -1.30456209  1.09542416]
 [ 0.14108838  1.31893723  0.23927514 -1.36444768 -2.20400749]
 [ 2.04632212 -1.43189111 -0.11878581  0.65114416  0.20398021]] 

array2:
 [[-0.07335825 -0.0922523  -0.48953405  0.715922    1.11445459]
 [-1.35173175  1.03121226  0.19067578  1.73369797 -0.02764025]
 [-0.02948347 -0.19636667  0.08807942 -0.82353622 -0.94894108]
 [ 0.81097264  0.65631292  2.32978042 -0.79605461 -0.58539472]
 [-0.07154776 -0.16385262 -0.83966954 -0.64667236 -2.47436113]]

Fusión condicional:
[[-0.32191201 -1.52187377 -0.48953405  0.57624139 -1.16257721]
 [-1.35173175 -1.21703311 -0.23323835 -0.27868128 -1.58374534]
 [-0.02948347 -0.19636667  0.08807942 -1.30456209 -0.94894108]
 [ 0.14108838  0.65631292  0.23927514 -1.36444768 -2.20400749]
 [-0.07154776 -1.43189111 -0.83966954 -0.64667236 -2.47436113]]

Anidación 

### Funciones matemáticas y estadísticas

NumPy ofrece un amplio conjunto de funciones matemáticas y estadísticas que se pueden aplicar sobre ndarrays. A continuación se pueden encontrar los ejemplos más típicos (hay algunas más que pueden consultarse en la documentación oficial de NumPy).<br/>
<ul>
<li><b>sum:</b> Suma de elementos.</li>
<li><b>mean:</b> Media aritmética de los elementos.</li>
<li><b>median:</b> Mediana de los elementos.</li>
<li><b>std:</b> Desviación estándar de los elementos.</li>
<li><b>var:</b> Varianza de los elementos.</li>
<li><b>min:</b> Valor mínimo de los elementos.</li>
<li><b>max:</b> Valor máximo de los elementos.</li>
<li><b>argmin:</b> Índice del valor mínimo.</li>
<li><b>argmax:</b> Índice del valor máximo.</li>
<li><b>cumsum:</b> Suma acumulada de los elementos.</li>
<li><b>cumprod:</b> Producto acumulado de los elementos.</li>
</ul>

Todas estas funciones pueden recibir, además del ndarray sobre el que se aplicarán, un segundo parámetro llamado <b>axis</b>. Si no se recibe este parámetro las funciones se aplicarán sobre el conjunto global de los elementos del ndarray, pero si se incluye, podrá tomar dos valores:
<ul>
<li>Valor 0: Aplicará la función por columnas</li>
<li>Valor 1: Aplicará la función por filas</li>

In [5]:
array = np.random.randn(5,4)

print("array:\n",array,"\n")

print("\nOperación global:")
print(np.sum(array))

print("\nOperación por columnas:")
print(np.sum(array, 0))

print("\nOperación por filas:")
print(np.sum(array, 1))

array:
 [[-0.10847265  0.354711    0.16827281 -0.22815404]
 [ 1.09750307 -0.92153408 -0.00622435 -1.44022786]
 [ 0.5697455  -0.97910691 -0.81195628 -0.83867949]
 [ 1.05704658 -1.14811228  1.64003176 -1.08575686]
 [-1.2370986   0.33452549 -0.63173685 -0.62535081]] 


Operación global:
-4.840574856253628

Operación por columnas:
[ 1.37872389 -2.35951679  0.35838709 -4.21816906]

Operación por filas:
[ 0.18635712 -1.27048322 -2.05999718  0.4632092  -2.15966077]


Adicionalmente algunas de estas funciones pueden ser utilizadas como "métodos" de los ndarray y no sólo como funciones sobre los mismos. En este caso la sintáxis cambiará y se utilizará la notación "ndarray.funcion()" 

In [6]:
print(array.sum())
print(array.sum(0))
print(array.sum(1))

-4.840574856253628
[ 1.37872389 -2.35951679  0.35838709 -4.21816906]
[ 0.18635712 -1.27048322 -2.05999718  0.4632092  -2.15966077]


### Operaciones sobre ndarrays booleanos

Dado que, internamente, Python trata los valores booleanos True como 1 y los False como 0, es muy sencillo realizar operaciones matemáticas sobre estos valores booleanos de forma que se puedan hacer diferentes chequeos. Por ejemplo...

In [7]:
array = np.random.randn(5,5)

print("array:\n",array,"\n")

print("\nElementos mayores que 0")
print((array>0).sum())

print("\nElementos menores que la media")
print((array < array.mean()).sum())


array:
 [[ 0.13283005  0.4830224   0.68838994  1.19060459 -2.05955752]
 [-1.07292916 -0.26150898 -0.71344026  0.19870117  0.40830547]
 [ 1.64314128  0.42087878 -1.57105494 -1.38314558 -0.40660443]
 [-2.0865984  -1.03249123 -0.46459606 -0.8345946   0.19866413]
 [-1.15227681  0.32380771  1.70105273 -0.85383428 -0.42233526]] 


Elementos mayores que 0
11

Elementos menores que la media
13


NumPy también pone a nuestra disposición dos funciones de chequeo predefinidas sobre ndarrays booleanos:<br/>
<ul>
<li><b>any:</b> Para comprobar si alguno de los elementos es True.</li>
<li><b>all:</b> Para comprobar si todos los elementos son True.</li>
</ul>

In [8]:
print("Alguno de los elementos es igual a 0")
print((array==0).any())

print("\nTodos los elementos son menores que 0")
print((array<0).all())

print("\nTodos los elementos entan en un rango")
print( ((array >= -2) & (array <=2)).all() )

Alguno de los elementos es igual a 0
False

Todos los elementos son menores que 0
False

Todos los elementos entan en un rango
False


### Ordenación de ndarrays

In [9]:
array = np.random.randint(10,size=(2,5))
print("array:\n",array)

print("\nDatos ordenados")
print(np.sort(array)) # sort along the last axis

print("\nDatos ordenados según el primer eje")
print(np.sort(array, axis=0)) # sort along the first axis

print("\nDatos ordenados de forma unidimensional")
print(np.sort(array, axis=None)) # sort the flattened array


array:
 [[3 2 7 2 1]
 [3 2 8 8 7]]

Datos ordenados
[[1 2 2 3 7]
 [2 3 7 8 8]]

Datos ordenados según el primer eje
[[3 2 7 2 1]
 [3 2 8 8 7]]

Datos ordenados de forma unidimensional
[1 2 2 2 3 3 7 7 8 8]


### Funciones de conjunto

NumPy permite realizar tratamientos sobre un ndarray asumiendo que el total de los elementos del mismo forman un conjunto.<br/>
<ul>
<li><b>unique:</b> Calcula el conjunto único de elementos sin duplicados.</li>
<li><b>intersect1d:</b> Calcula la intersección de los elementos de dos arrays.</li>
<li><b>union1d:</b> Calcula la unión de los elementos de dos arays.</li>
<li><b>in1d:</b> Calcula un array booleano que indica si cada elemento del primer array está contenido en el segundo.</li>
<li><b>setdiff1d:</b> Calcula la diferencia entre ambos conjuntos.</li>
<li><b>setxor1d:</b> Calcula la diferencia simétrica entre ambos conjuntos.</li>
</ul>

In [10]:
array1 = np.array([6, 0, 0, 0, 3, 2, 5, 6])
array2 = np.array([7, 4, 3, 1, 2, 6, 5])

print("conjunto único array1:", np.unique(array1))
print("intersección:", np.intersect1d(array1,array2))
print("unión:", np.union1d(array1,array2))
print("está contenido en:", np.in1d(array1,array2))
print("elementos del primer array no contenidos en el segundo", np.setdiff1d(array1,array2))
print("diferencia simétrica:", np.setxor1d(array1,array2))

conjunto único array1: [0 2 3 5 6]
intersección: [2 3 5 6]
unión: [0 1 2 3 4 5 6 7]
está contenido en: [ True False False False  True  True  True  True]
elementos del primer array no contenidos en el segundo [0]
diferencia simétrica: [0 1 4 7]
