# NumPy - Ejercicios

### 1. Crea una función que reciba como parámetro un número n y devuelva una matriz cuadrada (dos dimensiones) de nxn donde los elementos de la matriz principal valgan 1 y el resto valgan n.

In [1]:
import numpy as np

In [2]:
def square_matrix(n):
    a = np.full((n,n),n)
    np.fill_diagonal(a, 1)
    return a

square_matrix(5)   

array([[1, 5, 5, 5, 5],
       [5, 1, 5, 5, 5],
       [5, 5, 1, 5, 5],
       [5, 5, 5, 1, 5],
       [5, 5, 5, 5, 1]])

### 2. Crea una función que reciba dos números n y m que definirán ancho y alto de una matriz de nxm elementos numéricos secuenciales y un booleano que definirá si se debe devolver la matriz generada (False) o su traspuesta (True).

In [3]:
def matrix(n, m, transpose=False):
    matrix = np.array(range(n*m))
    if transpose == True:
        return np.matrix.transpose(matrix.reshape(n,m))    
    return matrix.reshape(n,m)
 
print(matrix(5,10))
print("\n", matrix(5,10,True))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

 [[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]


### 3. Crea una función que genere un esquema de tablero de ajedrez (con valores 1 y 0, enteros) en base a dos parámetros: la dimensión (cuadrada) del tablero n y un flag que indique si el primer elemento de la primera fila debe ser un 1 (True) o un 0 (False).

In [4]:
def chessboard(n, flag = True):
    chboard = np.zeros(n*n, dtype=np.int16)
    if flag == True:
        chboard[::2] = 1
    else:
        chboard[1::2] = 1
    return chboard.reshape(n,n)

n=5
print(chessboard(n))
print("\n",chessboard(n,False))

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]

 [[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


### 4. Crea una función que reciba dos arrays y genere un array que tenga 0 en todos los elementos y 1 en aquellos elementos del primer array que sean mayores que su equivalente del segundo array.

In [5]:
def matrix(arr1, arr2):
    arr_result = arr1 - arr2
    arr_result[arr_result < 0] = 0
    arr_result[arr_result > 0] = 1
    return arr_result

array1 = np.random.randint(10, size=(4,4))
array2 = np.random.randint(10, size=(4,4))

matrix(array1, array2)

array([[1, 1, 1, 0],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1]])

### 5. Crea una función que reciba un array y una tupla de enteros y devuelva la matriz resultante de seleccionar los índices de la tupla aplicados desde el final.

In [6]:
array = np.random.randint(10, size=10)
tupla = tuple(np.random.randint(10, size=10))

def build_array(p_array, p_tuple):
    return np.array([p_array,p_tuple[::-1]])

build_array(array, tupla)

array([[5, 2, 1, 7, 2, 7, 9, 9, 3, 6],
       [5, 0, 2, 2, 7, 3, 1, 3, 6, 4]])

### 6. Replica la función del ejercicio 4 utilizando la función np.where

In [7]:
def matrix(arr1, arr2):
    arr_result = np.where(arr1 - arr2 < 0, 0, 1)
    return arr_result

array1 = np.random.randint(10, size=(4,4))
array2 = np.random.randint(10, size=(4,4))

matrix(array1, array2)

array([[1, 0, 1, 1],
       [1, 1, 0, 1],
       [0, 1, 0, 1],
       [1, 1, 0, 0]])

### 7. Crea una función que reciba una matriz y chequee si hay o no algún valor negativo en la misma.

In [8]:
def any_negative(matrix):
    return np.any(a=matrix<0)

print("Example 1")
matrix = np.random.randn(4,4)
print(any_negative(matrix))
print(matrix)

print("Example 2")
matrix = np.random.randint(10, size=(4,4))
print(any_negative(matrix))
print(matrix)

Example 1
True
[[ 0.67611274  0.1092629   0.42015929 -1.12687087]
 [-1.15649395  0.66333102 -2.27359962  0.25734005]
 [-0.34925714 -0.71860931 -0.27004875  0.61074066]
 [-0.90674318  0.90242589  1.50916383  0.17807893]]
Example 2
False
[[1 9 8 9]
 [2 1 4 7]
 [3 5 4 8]
 [1 8 8 7]]


### 8. Crea una función que utilizando la del ejercicio anterior, sume el valor absoluto de todos los elementos negativos de una matriz recibida como parámetro o devuelve "No hay negativos" en caso de que no los haya.

In [9]:
def sum_abs_negative_values(matrix):
    if any_negative(matrix):
        return np.sum(np.abs(matrix[matrix<0]))
    return "No hay negativos"

print("Example 1")
matrix = np.random.randint(low=-5, high=5, size=(4,4))
print(sum_abs_negative_values(matrix))
print(matrix)

print("Example 2")
matrix = np.random.randint(5, size=(4,4))
print(sum_abs_negative_values(matrix))
print(matrix)

Example 1
33
[[-2 -4  1 -5]
 [ 3 -1  2 -5]
 [ 4  1  4 -3]
 [-4 -5 -4  1]]
Example 2
No hay negativos
[[4 3 2 3]
 [0 3 0 3]
 [1 0 1 4]
 [4 0 4 4]]


### 9. Crea una función que reciba una matriz unidimensional con nombres, una matriz con el mismo ancho que la matriz de nombres que contenga valores numéricos y un nombre de los de la primera lista. Deberá devolver, en una tupla, los descriptivos (mínimo, máximo, media, mediana y desviación típica) del vector de valores "asociado" al nombre seleccionado por posición. Ten en cuenta que el nombre introducido puede no estar en el listado y contrólalo.

In [10]:
def selected_row_stats(names, matrix, name):
    if(name in names):
        row_selected = matrix[names == name]
        return tuple((row_selected.min(),
                      row_selected.max(), 
                      row_selected.mean(),
                      row_selected.std(),
                      np.median(row_selected)))    
    return str(name + " is not in " + np.array2string(names))

print("Scenario 1\n")
names = np.array(["ciencias", "mates", "lengua", "reli"])
matrix = np.random.randint(10,size=(len(names),len(names)))
name = "mates"
print("data:\n", matrix)
print("\nselected row", matrix[names == name])
print("\nstatistics", selected_row_stats(names, matrix, name))

print("\nScenario 2\n")
name = "phisics"
print(selected_row_stats(names, matrix, name))

Scenario 1

data:
 [[5 6 1 3]
 [8 8 2 5]
 [9 8 3 3]
 [9 4 8 6]]

selected row [[8 8 2 5]]

statistics (2, 8, 5.75, 2.48746859276655, 6.5)

Scenario 2

phisics is not in ['ciencias' 'mates' 'lengua' 'reli']


### 10. Crea una función que reciba dos matrices y devuelva la secuencia ordenada de la union de los elementos únicos de ambas.

In [11]:
def merged_matrix(matrix1:np.ndarray, matrix2:np.ndarray):
    return np.union1d(np.unique(matrix1), np.unique(matrix1))

matrix_1 = np.random.randint(20, size=(10))
matrix_2 = np.random.randint(20, size=(10))

print(matrix_1)
print(matrix_2)

merged_matrix(matrix_1,matrix_1)

[10  2  6  2  6 15 12  3  3  8]
[ 6  0 10 19 11  4 14  7 18  9]


array([ 2,  3,  6,  8, 10, 12, 15])

### 11. Crea una función que reciba un número n, genere una matriz nxn a partir de una secuencia numérica y escriba la misma en un fichero cuyo nombre se recibirá también como parámetro. Hazlo con ficheros binarios.

In [12]:
def write_binary_file(n,binary_file_name):
    sequence = np.random.randn(n,n)
    np.save(binary_file_name, sequence)
    
write_binary_file(5, "numpy_file")
print(np.load("numpy_file.npy"))

[[ 0.61864106  0.38284348 -0.27949407 -0.54855203  1.11130291]
 [-1.14767228 -0.68878563 -1.40961464 -0.09436063 -0.87864163]
 [-0.00576056  0.87147103  0.10531019 -0.91465929 -0.47847557]
 [-0.07697044  0.04692363  1.36491535  0.21888146 -0.12953974]
 [ 1.66988411  1.69985085  0.78191993 -0.91127908 -1.95883347]]


### 12. Crea una función que reciba el nombre de un fichero binario de NumPy, lo lea como binario, sume el contenido del mismo por filas y guarde el resultado en un fichero de texto con el mismo nombre (pero extensión txt).

In [13]:
def rows_sum_binary_file(file_name):
    array = np.load(file_name+".npy", allow_pickle=True)
    sum_rows_array = np.sum(array, axis=1)
    np.savetxt(file_name+".txt", sum_rows_array, delimiter=',')

file_name = "numpy_file"
rows_sum_binary_file(file_name)

np.loadtxt(file_name+".txt",delimiter=',')

array([ 1.28474135, -4.21907481, -0.42211419,  1.42421027,  1.28154234])

### 13. Crea una función que reciba dos enteros n y m, genere dos matrices aleatorias (normales 0,1) de dimensiones nxm y mxn y haga el producto escalar de ambas para obtener una matriz nxn. Deberá devolver una tupla con las tres matrices.

In [14]:
def dot_matrix(n,m):
    matrix_a = np.random.randn(n,m)
    matrix_b = np.random.randn(m,n)
    dot_matix = np.dot(matrix_a, matrix_b)
    return tuple((matrix_a, matrix_b, dot_matix))

dot_matrix(3,4)

(array([[ 1.75417893,  0.6923276 , -1.13073449,  0.46125232],
        [-2.19812131,  0.50811683,  0.55644116,  0.06254384],
        [-0.49963861, -1.00048606, -1.17700036,  0.84856853]]),
 array([[ 0.02936129,  0.65688452, -0.20619505],
        [ 1.63123899, -0.2291421 ,  0.15968284],
        [ 0.6274632 , -0.58781962, -0.9419607 ],
        [ 2.39973316, -1.15918654,  0.03479731]]),
 array([[ 1.57824493,  1.12364203,  0.83000762],
        [ 1.26355521, -1.95992984,  0.01240992],
        [-0.34888828, -0.3907367 ,  1.08147854]]))

### 14. Crea una función que reciba una matriz de datos y un entero n y devuelva una muestra (muestreo aleatorio simple) de n elementos.

In [15]:
def random_sampling(matrix, n):
    return np.random.choice(matrix, n)

matrix = np.random.randint(50, size=10)
print(matrix)

random_sampling(matrix,3)

[26 20 49 13  7 29 17  6 13 10]


array([29, 17, 17])